### ISSUE TITLE
[5.0 beta and stable] Gaps between skin and walls. (Caused by skin removal width)

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#11881]
### Application Version

5.0 beta

### Platform

win10

### Printer

custom fff

### Reproduction steps

Sliced the benchy, see attached project

### Actual results

There is a gap between the walls and the skin. A few dots of infill is placed where there is room.

### Expected results

No gap.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

Layer 38:
![skin gap](https://user-images.githubusercontent.com/32172100/164688216-c84a0372-ae57-4d88-ad07-8f189af508f4.jpg)
[skin gap.3mf.zip](https://github.com/Ultimaker/Cura/files/8539840/skin.gap.3mf.zip)

**Comment by nallath** [comment]
Damnit. I thought we fixed that :(

**Comment by printingotb** [comment]
Perhaps one of the other bugs will offer some clues.

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your report.
Will bring it up with the team. Keep you posted.

**Comment by Sonicboom247** [comment]
i wasted so much filament trying to figure this out... turns out Filter out gaps between walls has been removed. 4.13.1 on left, 5Beta on right....
![gaps](https://user-images.githubusercontent.com/84334417/166557542-6a60a07a-5e24-4284-928c-ae535522a061.jpg)
.

**Comment by printingotb** [comment]
Still present in the stable release. The culprit is skin removal width.
A more extreme example with Top skin removal width set to 4mm (this is the top most layer):
![Screenshot 2022-05-18 110053](https://user-images.githubusercontent.com/32172100/169000944-16de22e2-db86-4224-861b-d164023cc582.jpg)

**Comment by casperlamboo** [comment]
Hi @printingotb thanks for reporting the issue and apologies for waiting this long to get back to you.

I investigated the issue but I expect this is _expected behavior_. This probably is not what you wanted to hear but allow me to explain my reasoning.

The skin are is calculated by looking at a certain amount of layers above and see what areas on the current layer are no longer within the model. For the benchy model a few layers above layer 37 looks something like.
![Screenshot 2023-01-09 at 11 11 41](https://user-images.githubusercontent.com/6638028/211284809-8264b79b-5d99-428b-8581-5f23fd07d06d.png)
Note the railing at the back side of the benchy model. As there is actual parts of the model above the area you highlighted I do expect these area's not to be filled in with skin.

Please let me know if you agree with my assessment, and if not let me know why these area's should be filled with skin anyway.

**Comment by printingotb** [comment]
Hello there @casperlamboo!
Thank you for your reply but I can't imagine this is expected behavior. It should not remove parts of the skin of a flat area with nothing above. That is how the settings guide describes it and also how it worked in older Cura.

Here's an example with some rectangles: (Please note that this is the topmost layer of flat surfaces)

At 7mm removal width it starts eating away at corners of the skin of all parts. This is in my opinion not intended. 

If it was intended to remove flat skin with nothing above, I would expect it to only remove any areas that are thinner than the removal width entirely and not remove parts of an area that is wider than the removal width. 

![Removal widht 7](https://user-images.githubusercontent.com/32172100/211524688-6e595721-051a-4f51-b465-d620c69f9417.jpg)
![Removal width 19](https://user-images.githubusercontent.com/32172100/211524708-6c0680d9-d7dd-4a03-8f02-f2494de08aa0.jpg)
![20 angled](https://user-images.githubusercontent.com/32172100/211524750-af8a26bd-7135-4e1d-8722-0367d2d315c5.jpg)
![4131](https://user-images.githubusercontent.com/32172100/211528861-217f2f51-8aa1-490a-89bb-2cab77aab04b.jpg)
![Skin removal tooltip](https://user-images.githubusercontent.com/32172100/211524929-777d108e-23c9-4638-bf30-9774e59c917a.jpg)
[Various shapes.3mf.zip](https://github.com/Ultimaker/Cura/files/10381536/Various.shapes.3mf.zip)

**Comment by casperlamboo** [comment]
Ah yes, I agree that that is indeed not intended behavior. Thank you for the elaborate explanation and the included project files. I will update our backlog ticket.

However, I do think that this is a separate issue from the benchy model. Once this is fixed I predict the benchy example will have the same "gap" in skin as there is "inside geometry" above this area.

**Comment by printingotb** [comment]
> Ah yes, I agree that that is indeed not intended behavior. Thank you for the elaborate explanation and the included project files. I will update our ticket.

Great, thanks!

>However, I do think that this is a separate issue from the benchy model. Once this is fixed I predict the benchy example will have the same "gap" in skin as there is "inside geometry" above this area.

Yeah that makes sense.
