### ISSUE TITLE
Unable to exit Move Model function

### ISSUE THREAD

**Issue by Barry37** [Ultimaker/Cura#1211]
Cura (2.3.1) sticks on Move model (a multiple of 6 models). Moving the mouse just keeps moving the model. The X position this time is now 28766mm, so the models are way out of the print area (and invisible). The only way I've found to get out of this is to Force Quit (Mac OS X). It's not possible to type a value in the "Move" panel, or choose "Scale" etc.
I can't think of a reason for actually being able to move a model off the print area (and it then being auto sliced while unprintable).

**Comment by nallath** [comment]
This is a bug that should be fixed for 2.4

**Comment by vdesmedt** [comment]
I have exactly the same issue in 2.4 but only with big objects.  I have attached one of the object with which I encounter the trouble.
[Body2.stl.zip](https://github.com/Ultimaker/Cura/files/818476/Body2.stl.zip)

**Comment by Ghostkeeper** [comment]
Doesn't reproduce for me with that model. Perhaps it depends on the build volume if it occurs only with big models. What printer are you using?

**Comment by vdesmedt** [comment]
UMO. I have checked the dimensions in my settings which are correctly set to roughly 200/200/200 mm
I'm running the OS X version of cura

**Comment by Ghostkeeper** [comment]
Still doesn't reproduce :( Though I am running the most recent development environment, and on Ubuntu rather than OSX. Shall we hope that it's fixed in there?

One more thing we could try is to share a .curaproject file rather than an STL model. I doubt that'll make any difference though.
