### ISSUE TITLE
Aborting print -> auto home Y-X-Z end ?

### ISSUE THREAD

**Issue by Jhinta** [Ultimaker/Cura#2307]
When printing with 2.6 and pressing abort, the print just wil halt
When printing with 2.7 and pressing abort it seems like its restarting start-code. ( home y-x and z)

Both 2.7 and 2.6 use the same start and end code.
Whats wrong here?

End-Code
`M104 S0 ;extruder heater off
M140 S0 ;heated bed heater off (if you have it)
G91 ;relative positioning
G1 E-1 F300 ;retract the filament a bit before lifting the nozzle, to release some of the pressure
G1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more
G28 X0 Y0 ;move X/Y to min endstops, so the head is out of the way
G90 ;absolute positioning
G1 Y190 F9000 ;use this line if you want the bed to move to the front. delete if not.
M84 ;steppers off`

**Comment by Ghostkeeper** [comment]
Yes, I added this here: 6d2b46244f910cc5f09b07bdde1955bdcde77afb

Otherwise when you abort, it would keep the nozzle stuck on the print and make a mess. This was intended.

It's not the start or end code that it executes. It just homes the nozzle now.

**Comment by Ghostkeeper** [comment]
Is there anything wrong with this approach?

**Comment by Jhinta** [comment]
Yes, its also homes Z , it sould not do that .
only do home all but Z (Z save zone problems !)
And why would one do a hame z when there is a abort?

**Comment by Jhinta** [comment]
Yes, its also homes Z , it sould not do that .
only do home all but Z (Z save zone problems, and when you have a big/multi project on border it will distroy your project) !)
And why would one do a home Z when there is a abort?

**Comment by Jhinta** [comment]
more like this i think , move Z up a litle and then home Y & X
self._sendCommand("G1 Z+0.5 ")
self._sendCommand("G28 X Y")

**Comment by nickthetait** [comment]
@Ghostkeeper this is a dangerous operation only for printers that home Z at the bottom

**Comment by fieldOfView** [comment]
It is also an issue with Ultimaker Original, which homes at the bottom. I would say it is not necessary to home the z-axis at all.

A longer term solution would be to have an abort-gcode machine-setting in Cura (possibly along with pause-gcode and resume-gcode settings).

**Comment by Ghostkeeper** [comment]
Thanks to @fieldOfView's fix, it now only homes X and Y, not Z.

**Comment by Ghostkeeper** [comment]
Now that I think about it, the same can happen when printing in one-at-a-time mode, when aborting while printing the second object.

**Comment by fieldOfView** [comment]
Moving up 10mm in relative mode may be all that can be done safely.

**Comment by jack0088** [comment]
So is this fix included with 2.7.0 or when will it be? Because on my Prusa i3 MK2 it just home'ed everything on canceling (including the Z-axis and crashed into the printing).

**Comment by fieldOfView** [comment]
This is fixed with Cura 3. A beta is available through the Ultimaker forum

**Comment by EnumC** [comment]
@fieldOfView Running Cura 3.0.4 and it's still auto homing Z on abort. This is especially dangerous for machines that use fixed probe, as auto homing Z will cause the probe to go out of bed and crack the glass bed underneath.

**Comment by fieldOfView** [comment]
Unfortunately a number of fixes were made to the master branch before the release of 3.0 that did not get included in 3.0. This is one of them. This is probably not going to be fixed until Cura 3.1.

**Comment by asantoni** [comment]
This is still an issue as of Cura 3.2.0. Can we reopen this issue to reflect the bug status?

**Comment by collse** [comment]
has this been addressed? Where can I change the abort gcode in Cura 3.5.1?

**Comment by SteveC00k** [comment]
When the printer homes on my printer because of the sides it hits the edge and bends the hotend. Why would you not place the ability to control this. :/
