### ISSUE TITLE
"Arrange All Models" in "One at a Time" print sequence

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4192]
**Application Version**

4.3.1

**Platform**

Windows 10

**Printer**

Creality CR-10S
[CCR10_balance.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2259714/CCR10_balance.curaproject.3mf.zip)

**Steps to Reproduce**

First 4 photos show sequence
Load model
Duplicate model to 3
Switch to "One at a Time" print sequence
Select "Arrange All Models"

**Actual Results**

Fifth photo shows result
Two models positioned off build plate

**Expected results**

Sixth photo shows expected arrangement
Sixth to Eighth photos show XY positions of models

I understand that rotating a model to fit might make "Arrange All Models" more complicated to program, but using just the max width and height of the models required print clearance, should make it easier to calculate.

**Additional Information**

![screenshot 40](https://user-images.githubusercontent.com/18093484/43679335-8af35b92-981b-11e8-9455-13952f7a6994.png)
![screenshot 41](https://user-images.githubusercontent.com/18093484/43679336-8b0ebb6c-981b-11e8-9f9d-a07bef8ef98c.png)
![screenshot 42](https://user-images.githubusercontent.com/18093484/43679337-8b2704ec-981b-11e8-8f72-da3c6eae598d.png)
![screenshot 43](https://user-images.githubusercontent.com/18093484/43679338-8b3fde90-981b-11e8-9911-98f37949548e.png)
![screenshot 44](https://user-images.githubusercontent.com/18093484/43679339-8b58c054-981b-11e8-935e-a14a0a032768.png)
![screenshot 45](https://user-images.githubusercontent.com/18093484/43679340-8b725be0-981b-11e8-8d1e-d5361fc1a1c2.png)
![screenshot 46](https://user-images.githubusercontent.com/18093484/43679341-8b8c01f8-981b-11e8-8d99-377ac6b1f9c4.png)
![screenshot 47](https://user-images.githubusercontent.com/18093484/43679342-8ba44b50-981b-11e8-8a3d-192e322409ec.png)

**Comment by ChrisTerBeke** [comment]
The grey area around the object indicates the nozzle can't go there (because of one-at-a-time mode which requires clearance between the objects so that the extruder doesn't collide with them). Adding rotation to auto-arrange makes it a mathematical problem of a completely different category...

**Comment by fieldOfView** [comment]
Note that there is no such thing (yet) as Cura 4.3.1. You probably mean Cura 3.4.1.

**Comment by FynDestiny** [comment]
Yes, I meant 3.4.1 . Slip of the digits.

**Comment by FynDestiny** [comment]
I understand adding the rotation would complicate matters.

But even without the rotation, two of the three models can be positioned perfectly well in the build area. As you can see in the last few photos. Leaving just the one in need of "adjustment" by the user, to either make it fit or remove it

**Comment by Ghostkeeper** [comment]
There are two collision areas in one-at-a-time mode. The inner area of one object is not allowed to intersect with the outer area of the other object. The arranger works by painting a pixel grid of areas that are filled with models. Ideally, when checking whether an object is allowed to be placed there it should use a different area than when filling the pixels that are obstructed. This would pack these objects much more efficiently.

**Comment by nallath** [comment]
Except that it would need to use 2 different areas (that's what the push free is doing). The arranger is totally not built to handle this at the moment.

So unfortunately, this is an issue, we should fix it at some point, but it's not something that's used all that often, so we probably wont.

**Comment by Bob90** [comment]
Just want to add that the arranger also sets the models in from the edges, but you would normally be able to print there so the models along an edge could be arranged much further out and provide more space.

**Comment by RandomGgames** [comment]
Wow this hasn't been improved in 4 years. Could we get this added? There are many instances where there are a lot more models that could fit onto a plate by manually placing them. The auto arrange works great in normal mode but not in one at a time... And I'm using 4.13.1!!

**Comment by behold81** [comment]
This is STILL an issue!! 

Surely there are a few things that could be taken in to account to solve it. Also, the grey areas can overlap the edge of the build area as this is dead space.
