### ISSUE TITLE
"Collecting Data" popup since v3.6.0

### ISSUE THREAD

**Issue by lowlyocean** [Ultimaker/Cura#5000]
This annoying popup has been appearing every time I launch Cura,  and I have to click the X each time. Cura doesn't seem to remember my selection between runs.
![image](https://user-images.githubusercontent.com/13685818/50043745-bb814500-0047-11e9-8e65-ad9743908925.png)

**Comment by lowlyocean** [comment]
So will Cura collect statistics even when I click the X? Why isn't Deny an option?

**Comment by nallath** [comment]
You can disable it in the preferences menu. Since it's anonymized data, we don't even need to mention (or ask) this in the first place, but we decided to be transparent about it. 

It constantly asking is indeed a bug. What version are you running it on (I do recall that we fixed some things there some time ago, but i'm not a 100% sure)?

**Comment by lowlyocean** [comment]
I'm using 3.6.0 and see no place to disable in preferences menu. Can you provide screenshot?

**Comment by lowlyocean** [comment]
![image](https://user-images.githubusercontent.com/13685818/50196607-c66efa80-0311-11e9-877d-c261293568a9.png)
Found it, but it's already as I would expect it should be to disable the popups...

**Comment by Thisismydigitalself** [comment]
in terms of bandwidth the data you send out is close to nothing.
in return you get a free slicer and still, you don't have to share anything.

**Comment by thisiskeithb** [comment]
This bug is still present in Cura 4.0.

This notification is present at launch with the only options being Allow or close:
<img width="401" alt="screen shot 2018-12-19 at 12 23 36 am" src="https://user-images.githubusercontent.com/13375512/50207829-8402e900-0324-11e9-84b9-f4e87e333668.png">

This setting is disabled:
<img width="877" alt="screen shot 2018-12-19 at 12 24 14 am" src="https://user-images.githubusercontent.com/13375512/50207828-8402e900-0324-11e9-9fbd-777f58e5a372.png">

My firewall doesn't show any traffic to stats.ultimaker.com in recent months, but it's confusing and annoying to dismiss that popup when I've disabled the feature.

**Comment by nallath** [comment]
I'll look into it!

**Comment by nallath** [comment]
That's weird. With 4.0 I also have a "more info" link sitting next to the allow button. The message keeps popping up untill you pressed the allow button (once you do, it's gone for good).

**Comment by Liger0** [comment]
I can confirm I have always that popup.

**Comment by lowlyocean** [comment]
This issue is still present in 4.0.0 @LipuFei

**Comment by nallath** [comment]
This is fixed for 4.1
