### ISSUE TITLE
Loading gcode doesn't view initial layer

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#5219]
**Application Version**
Cura 4.0.0 BETA

**Platform**
Linux MInt

**Printer**
UM3

**Steps to Reproduce**
Load attached gcode
[Voronoi_2.gcode.zip](https://github.com/Ultimaker/Cura/files/2792186/Voronoi_2.gcode.zip)

**Actual Results**
![image](https://user-images.githubusercontent.com/8895761/51686030-d86a4a00-1fef-11e9-998d-666e05c55205.png)

**Expected results**
![image](https://user-images.githubusercontent.com/8895761/51686053-e7e99300-1fef-11e9-8d14-a2d4169d817b.png)
The brim should be shown

**Additional Information**
Generated using surface mode if I remember correctly, but I can't imagine that's relevant.
Generated using older version of Cura for an UM3.

**Comment by Ghostkeeper** [comment]
It doesn't seem to happen with your g-code in the current state of 4.0:
![screenshot from 2019-01-25 11-55-38](https://user-images.githubusercontent.com/2448634/51741822-410d0180-2098-11e9-9aad-1e58048a7151.png)

I can't reproduce this. Maybe it has been fixed in the meanwhile?

**Comment by BagelOrb** [comment]
I'm so damn stupid.

I most probably just had Helper parts disabled in the layer view.

I keep getting confused by the layer view. 
Because when you scroll through a single layer everything is visualized I keep forgetting that I have disabled the visualization of helper parts.
Even when you have disabled the visualization of e.g. helper parts they will still shown when scrolling through a layer with the horizontal play bar.
Would you consider that as a bug?

**Comment by Ghostkeeper** [comment]
> Would you consider that as a bug?

Sorta yes. I knew about it, but wasn't bothered enough to really do something about it.

**Comment by BagelOrb** [comment]
Yeah same here.
