### ISSUE TITLE
Cannot re-preview UM S5 gcode / ufp

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#6663]
**Application version**
latest

**Platform**
Linux mint

**Printer**
S5

**Reproduction steps**
1. slice
2. save toolpaths
3. load model and quickly delete it (workaround for another bug which causes the gcode preview not to be flushed when switching to a different model)
4. load in .gcode or .ufp saved in step 2

**Actual results**
Preview shows massive overextrusion

**Expected results**
Preview the same as after step 1

**Additional information**
project, gcode, ufp
[S5_dual_preview.zip](https://github.com/Ultimaker/Cura/files/3852263/S5_dual_preview.zip)

![image](https://user-images.githubusercontent.com/8895761/68957410-4293eb80-07ca-11ea-9136-80b0b41b7e56.png)

**Comment by BagelOrb** [comment]
Free screenshot:
![image](https://user-images.githubusercontent.com/8895761/68957471-65be9b00-07ca-11ea-8897-1e99f438c754.png)

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this problem. I tried your reproduce steps (slice, save, load) and it displayed fine. Also the g-code files from your .zip archive seem to display normally:
![Screenshot from 2019-12-03 17-44-08](https://user-images.githubusercontent.com/2448634/70070864-35f5fc80-15ec-11ea-9d38-2a7e6264b3ac.png)

Has this been fixed in the meanwhile? Could you try on the latest master?

**Comment by BagelOrb** [comment]
Still reproduces on latest master for:
- UMS5_cube_2mm_dual.gcode
- UMS5_dual_brim.gcode
- UMS5_dual_brim.ufp

(PS: I can also reproduce it with the 3mf file, but I didn't update CuraEngine, so that test was inconclusive I guess.)

There's also some (other) update bug when loading gcode:
![image](https://user-images.githubusercontent.com/8895761/70071520-c553dd80-15f5-11ea-8f3c-c5552e775d80.png)

**Comment by Ghostkeeper** [comment]
Seems I just tried with the wrong g-code file from your .zip. Indeed with the 2mm_dual.gcode it reproduces. Somehow it seems to go wrong on layer 18 there on the first extrusion move. This is the g-code involved:

```
;TYPE:SKIN
G1 F1260 X160.644 Y120.551 E16.03071
M204 S5000
M205 X50 Y50
G0 F9000 X159.559 Y119.466
M204 S500
M205 X5 Y5
G1 F1260 X159.458 Y119.365 E16.0311
M204 S5000
M205 X50 Y50
G0 F9000 X159.469 Y119.271
;MESH:NONMESH
G0 F600 X159.469 Y119.271 Z1.9
G0 F9000 X159.413 Y120.001
;TIME_ELAPSED:92.302087
;LAYER:17
M204 S500
M205 X5 Y5
;TYPE:WALL-OUTER
;MESH:cube_10cm.stl(1)
G1 F1200 X160 Y119.409 E16.03567  ; <-- This line seems to be huge.
G1 X159.902 Y119.175 E16.03706
G1 X160 Y119.175
G1 X160.588 Y119.175 E16.04029
```

**Comment by Ghostkeeper** [comment]
Perhaps something goes wrong with the detected layer height?

**Comment by BagelOrb** [comment]
That sounds like a likely candidate!

Perhaps it thinks the Z1.9 belongs to the previous layer somehow.
