### ISSUE TITLE
Retraction Minimum Travel is lost in Cura 4

### ISSUE THREAD

**Issue by RealMook3d** [Ultimaker/Cura#6916]
Hello!
**Is your feature request related to a problem? Please describe.**
I'm frustrated that Retraction Minimum Travel was removed from options.

**Describe the solution you'd like**
It would be good to take it from Cura 3.6.0 (the latest 3* stable, right?) and make it open to users in Cura 4 and further versions. Place it in the "Expert" level, please. So it will change visually nothing for many many users.

**Describe alternatives you've considered**
I understand that probably it was removed to make the UI less cluttered with different options but the behaviour that now Cura decides where to retract or not is wrong. I've found cases where it "draws" just a circular shape (between other circles) and makes breaks with slightly angled straight lines which are produced with retracts. It's just an example. Some other excessive unwanted retract usages are highly possible. This wears off a filament, makes clogs more possible and stresses an extruder more when it's not necessary at all.
The default 0.8mm in 3.6.0 is way too small. For technical parts such a "jewelry" setting is unwanted in many cases. Cura already has different settings accessability levels. So if somebody is "scared" with a lot of new terms and options, it's always a choice to use "Basic" or "Advanced". 

**Affected users and/or printers**
"Makers" will benefit definitelly! I love Cura 4 for "Small Feature/Hole" option a lot. But it's missing that Retraction "fine tune" min. travel option. I've noticed that it was missing starting from some version. I was just searching and was sure that it was somewhere... But it's just gone. Feeling frustrated.

**Additional context**
edit: generally I found no difference about Bridging. Only that it was generated from a different corner of the same model. My concern is only about the lost option now.

**Comment by JustCost** [comment]
Support. A huge request to the developers of "Cura" to return this function and make it available for any printer. I can't turn it on. Even if the printer settings are custom.

**Comment by rburema** [comment]
It's still there, it just isn't visible. (You can go into 'manage settings visibility' and see that it's probably hidden by the currently active machine, since it's not _explicitly_ in one of the categories in the visibility profiles.)

Should be in the 'travel' category next release. Fixed in commit: https://github.com/Ultimaker/Cura/commit/9c0bd007144cf3249e2ff587c693820d1f6d6e2a

**Comment by RealMook3d** [comment]
I've created Custom FFF printer. A lot of settings has (i) sign and "hidden by the currently active machine". The same as I had with the previous printer activated.
What's the criteria for this? Still can't get this to work. Also a lot of handy features are unavailable to choose. Is it a bug?

**Comment by JustCost** [comment]
I also have this problem. The settings are hidden by the current printer - although I created a custom printer (all settings should be open) I think this is a bug of developers.
